"""credits_phase2

Revision ID: 3f6f9529f9e3
Revises: 5e965c7e158e
Create Date: 2026-09-30 03:37:20.946140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6f9529f9e3'
down_revision = '5e965c7e158e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_credit_policies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('booking_mode', sa.String(length=12), nullable=False),
    sa.Column('per_employee_monthly_cap', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', name='uq_company_credit_policy_company')
    )
    with op.batch_alter_table('company_credit_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_credit_policies_operator_id'), ['operator_id'], unique=False)

    op.create_table('room_blocks',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['conference_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_blocks', schema=None) as batch_op:
        batch_op.create_index('ix_room_block_range', ['room_id', 'start_at', 'end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_blocks_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_blocks_room_id'), ['room_id'], unique=False)

    with op.batch_alter_table('credit_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_show_minutes', sa.Integer(), nullable=False, server_default='15'))

    with op.batch_alter_table('pricing_plans', schema=None) as batch_op:
        batch_op.drop_column('meeting_room_access_included')
        batch_op.drop_column('meeting_room_overage_allowed')
        batch_op.drop_column('meeting_room_overage_rate')
        batch_op.drop_column('included_meeting_credits')
        batch_op.drop_column('meeting_credits_rollover')
        batch_op.drop_column('meeting_credit_unit')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_booking_allowed', sa.Boolean(), nullable=False, server_default=sa.false()))

    # A room can never be double booked, even by two people booking at the same instant.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
        op.execute("ALTER TABLE room_bookings ADD CONSTRAINT ex_room_booking_no_overlap "
                   "EXCLUDE USING gist (room_id WITH =, tsrange(start_at, end_at) WITH &&) "
                   "WHERE (status IN ('CONFIRMED', 'CHECKED_IN'))")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TABLE room_bookings DROP CONSTRAINT IF EXISTS ex_room_booking_no_overlap")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('credit_booking_allowed')

    with op.batch_alter_table('pricing_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_credit_unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('meeting_credits_rollover', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('included_meeting_credits', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('meeting_room_overage_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('meeting_room_overage_allowed', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('meeting_room_access_included', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.false()))

    with op.batch_alter_table('credit_settings', schema=None) as batch_op:
        batch_op.drop_column('no_show_minutes')

    with op.batch_alter_table('room_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_blocks_room_id'))
        batch_op.drop_index(batch_op.f('ix_room_blocks_operator_id'))
        batch_op.drop_index('ix_room_block_range')

    op.drop_table('room_blocks')
    with op.batch_alter_table('company_credit_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_credit_policies_operator_id'))

    op.drop_table('company_credit_policies')
    # ### end Alembic commands ###
