"""credits_core

Revision ID: 5e965c7e158e
Revises: 114eae0327a2
Create Date: 2026-09-30 02:41:42.860557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e965c7e158e'
down_revision = '114eae0327a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_seat_bands',
    sa.Column('min_seats', sa.Integer(), nullable=False),
    sa.Column('max_seats', sa.Integer(), nullable=False),
    sa.Column('monthly_credits', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_seat_bands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_seat_bands_operator_id'), ['operator_id'], unique=False)

    op.create_table('credit_settings',
    sa.Column('complimentary_share_pct', sa.Integer(), nullable=False),
    sa.Column('reserve_pct', sa.Integer(), nullable=False),
    sa.Column('pool_mode', sa.String(length=10), nullable=False),
    sa.Column('capacity_days_per_month', sa.Integer(), nullable=False),
    sa.Column('rollover_enabled', sa.Boolean(), nullable=False),
    sa.Column('rollover_cap', sa.Integer(), nullable=False),
    sa.Column('purchased_expiry_months', sa.Integer(), nullable=False),
    sa.Column('pay_per_use_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', name='uq_credit_settings_operator')
    )
    with op.batch_alter_table('credit_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_settings_operator_id'), ['operator_id'], unique=False)

    op.create_table('room_categories',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('credits_per_slot', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'name', name='uq_room_categories_operator_name')
    )
    with op.batch_alter_table('room_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_categories_operator_id'), ['operator_id'], unique=False)

    op.create_table('credit_allocations',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('monthly_credits', sa.Integer(), nullable=False),
    sa.Column('pending_monthly_credits', sa.Integer(), nullable=True),
    sa.Column('pending_from', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('(company_id IS NOT NULL) OR (user_id IS NOT NULL)', name='ck_credit_alloc_target'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'company_id', name='uq_credit_alloc_operator_company'),
    sa.UniqueConstraint('operator_id', 'user_id', name='uq_credit_alloc_operator_user')
    )
    with op.batch_alter_table('credit_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_allocations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_allocations_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_allocations_user_id'), ['user_id'], unique=False)

    op.create_table('credit_lots',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bucket', sa.Enum('BONUS', 'PASS', 'COMPLIMENTARY', 'PURCHASED', name='creditbucket'), nullable=False),
    sa.Column('granted', sa.Integer(), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('(company_id IS NOT NULL) OR (user_id IS NOT NULL)', name='ck_credit_lot_target'),
    sa.CheckConstraint('remaining >= 0', name='ck_credit_lot_remaining'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_lots_bucket'), ['bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_lots_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_lots_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_lots_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_lots_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_lots_user_id'), ['user_id'], unique=False)

    op.create_table('credit_ledger',
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('GRANT', 'USE', 'REFUND', 'PURCHASE', 'EXPIRE', 'FORFEIT', 'ADJUST', name='ledgertype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('room_booking_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['credit_lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_booking_id'], ['room_bookings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_ledger_entry_type'), ['entry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_ledger_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_ledger_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_ledger_room_booking_id'), ['room_booking_id'], unique=False)

    with op.batch_alter_table('conference_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_conference_rooms_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key(None, 'room_categories', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('credit_cost_per_hour')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('meeting_credits_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_credits_balance', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('conference_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_cost_per_hour', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conference_rooms_category_id'))
        batch_op.drop_column('category_id')

    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_ledger_room_booking_id'))
        batch_op.drop_index(batch_op.f('ix_credit_ledger_operator_id'))
        batch_op.drop_index(batch_op.f('ix_credit_ledger_lot_id'))
        batch_op.drop_index(batch_op.f('ix_credit_ledger_entry_type'))

    op.drop_table('credit_ledger')
    with op.batch_alter_table('credit_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_lots_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_lots_period'))
        batch_op.drop_index(batch_op.f('ix_credit_lots_operator_id'))
        batch_op.drop_index(batch_op.f('ix_credit_lots_expires_at'))
        batch_op.drop_index(batch_op.f('ix_credit_lots_company_id'))
        batch_op.drop_index(batch_op.f('ix_credit_lots_bucket'))

    op.drop_table('credit_lots')
    with op.batch_alter_table('credit_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_allocations_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_allocations_operator_id'))
        batch_op.drop_index(batch_op.f('ix_credit_allocations_company_id'))

    op.drop_table('credit_allocations')
    with op.batch_alter_table('room_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_categories_operator_id'))

    op.drop_table('room_categories')
    with op.batch_alter_table('credit_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_settings_operator_id'))

    op.drop_table('credit_settings')
    with op.batch_alter_table('credit_seat_bands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_seat_bands_operator_id'))

    op.drop_table('credit_seat_bands')
    # ### end Alembic commands ###
